apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: poison-pill-manager-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - daemonsets
  verbs:
  - create
  - get
  - patch
  - update
- apiGroups:
  - config.medik8s.io
  resources:
  - poisonpillconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.medik8s.io
  resources:
  - poisonpillconfigs/status
  verbs:
  - get
  - patch
  - update
