# permissions for end users to view poisonpillconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: poisonpillconfig-viewer-role
rules:
- apiGroups:
  - config.poison-pill.io.poison-pill.io
  resources:
  - poisonpillconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.poison-pill.io.poison-pill.io
  resources:
  - poisonpillconfigs/status
  verbs:
  - get
