apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: poison-pill-manager.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: PoisonPillConfig is the Schema for the poisonpillconfigs API
      displayName: Poison Pill Config
      kind: PoisonPillConfig
      name: poisonpillconfigs.config.poison-pill.io.poison-pill.io
      version: v1alpha1
  description: This poison pill controller is using an alternate mechanism for a node in a cluster to detect its health status and take actions to remediate itself in case of a failure. While not all remediation events can result in the node returning to a healthy state, the proposal does allow surviving parts of the cluster to assume the node has reached a safe state so that it’s workloads can be automatically recovered.
  displayName: poison-pill
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - remediation
  - fencing
  - poison pill
  - poison-pill
  - health
  - health check
  - recovery
  links:
  - name: Poison Pill Manager
    url: https://poison-pill-manager.domain
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
