apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: poison-pill-ds
  namespace: default
  labels:
    k8s-app: poison-pill
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      creationTimestamp: null
      labels:
        control-plane: controller-manager
    spec:
      priorityClassName: system-node-critical
      hostPID: true
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
        imagePullPolicy: Always
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - args:
        - --metrics-addr=127.0.0.1:8080
        command:
        - /manager
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: quay.io/nyehia/poison-pill:v0.0.1
        imagePullPolicy: Always
        name: manager
        securityContext:
          privileged: true
          hostPID: true
        ports:
        - containerPort: 30001
          hostPort: 30001
          name: p-pill-port
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        privileged: true
        hostPID: true
      terminationGracePeriodSeconds: 10
